#!/bin/bash

emph() {
  echo -e "\033[92m$1\033[0m"
}

input() {
  # $1 - input text, $2 - input variable name, $3 - default value
  read -p "$1 [default $(emph "$3")]: " input_value
  eval "$2=\${input_value:-\"$3\"}"
}

cd $(dirname $0)
cd ..

echo "Ports Configuration (Production Environment)"
input "client port" client_port 3000
input "database port" database_port 5432
echo

echo "Database Configuration"
input "timezone" timezone America/New_York
input "database name" database database
input "database username" pg_user postgres
read -p "database password [default $(emph "<strong autogenerated password>")]" pg_password
pg_password=${pg_password:-$(openssl rand -base64 256 | tr -d "\n=")}
input "name of schema (or dump) file to initialize database" schema schema.sql
echo
echo "PGAdmin (web-based ui for postgres) Configuration"
input "pgadmin email" pgadmin_email user@domain.com
read -p "pgadmin password [default $(emph "<strong autogenerated password>")]" pgadmin_password
pgadmin_password=${pgadmin_password:-$(openssl rand -base64 32 | tr -d "\n=")}

cat <<EOF > .env
CLIENT_PORT=$client_port
DATABASE_PORT=$database_port

TIMEZONE=$timezone
PG_USER=$pg_user
PG_PASSWORD=$pg_password
PG_DATABASE=$database
DUMP_FILE=$schema

# if using "make pgadmin", these are the credentials that will be used to access the database ui tool
PGADMIN_EMAIL=$pgadmin_email
PGADMIN_PASSWORD=$pgadmin_password
EOF